apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: afj-test-argo
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/VeriDID/afj-test-k8s-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: afj-test-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
