apiVersion: apps/v1
kind: Deployment
metadata:
  name: afj-test-deployment
  namespace: afj-test-app
  labels:
    app: afj-test
spec:
  selector:
    matchLabels:
      app: afj-test
  replicas: 1
  # strategy:
  # type: RollingUpdate
  template:
    metadata:
      labels:
        app: afj-test
    spec:
      containers:
        - name: docker-build
          image: "ghcr.io/veridid/dummy_app:sha-3af5081"
          imagePullPolicy: Always
          env:
            - name: AWS_COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: cognito-secret
                  key: AWS_COGNITO_USER_POOL_ID
            - name: AWS_COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cognito-secret
                  key: AWS_COGNITO_CLIENT_ID
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: cognito-secret
                  key: AWS_REGION
      imagePullSecrets:
        - name: ghcr-secret
